baseurl = "https://rebeccahe.github.io/"
title = "Personal Website"
theme = "nix"
languageCode = "en-us"

[menu]
  [[menu.header]]
    name = "projects"
    weight = 1
    url = "projects"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
  CvURL = "https://drive.google.com/file/d/1IL1Xd4Cz9BrdCxvPLWFksprtnNIqyjeL/view?usp=share_link"
  LinkedInID = "shunran-he-25b295223"
  GithubID = "rehesr"
  TwitterID = "beckyblur"
  InstagramID = "nic_not_nice"
  Email = "sh2662@cornell.edu"
  Name = "Rebecca He"
  HeaderUsername = "Rebecca"
  HeaderHostname = "HSR"
  About = "Hi, my legal name is Shunran He, but you can call me Rebecca. I am currently a Master of Financial Engineering student at Cornell University. Before that, I was a finance major at Peking University. I am a terrible cook, an amateur cinephile, and an aspiring quant."
  ProfilePicture = "/WechatIMG1658.jpg"
